import { type Metadata } from 'next';
import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menuOptions = [
    { id: 'dashboard', label: 'Dashboard', href: '/dashboard' },
    { id: 'user', label: 'User', href: '/user' },
    { id: 'tokens', label: 'Tokens', href: '/tokens' },
  ];

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable}`}>
          <header className="p-4 gap-4 bg-gradient-to-r from-blue-600 to-indigo-700 shadow-lg">
            {/* Navegación a la izquierda */}
            <nav className="container mx-auto px-4 py-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-8">
                  <SignedIn>
                    <ul className="hidden md:flex items-center space-x-6 text-lg font-semibold text-white">
                      {menuOptions.map((option) => (
                        <li key={option.id}>
                          <a href={option.href} className="">
                            {option.label}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </SignedIn>
                </div>
                <div className="flex items-center space-x-4">
                  <div className="flex items-center">
                    <UserButton />
                  </div>
                </div>
                <SignedOut>
                  <div className="flex justify-end gap-4 pr-4 text-gray-50">
                    <SignInButton mode="modal" />
                    <SignUpButton mode="modal" />
                  </div>
                </SignedOut>
              </div>
            </nav>
          </header>
          <main className="p-8">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
